# Site settings
title: hhhacker
email: webmaster@hhhacker.club
description: >
  hhhacker is a blog/community/store for hackers, developers, designers and entrepreneurs.
  We focus on quality - whether that's in our t-shirts, our code, or our blog posts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hhhacker.club" # the base hostname & protocol for your site
permalink: none

# Build settings
markdown: kramdown
